name: offline_gemini
description: Offline AI Assistant
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  typed_data: ^1.3.1
speech_to_text: ^6.3.0

flutter:
  uses-material-design: true
